### ISSUE TITLE
Daily limit for unauthenticated use exceeded

### ISSUE THREAD

**Issue by tjcrone** [intake/gdrivefs#15]
I'm probably doing something wrong here but I'm trying to open a Google Drive file for read-only anonymous access and I appear to be getting an error related to a daily limit. Currently on fsspec=0.8.4 and gdrivefs=HEAD. Am I doing it wrong? I would be happy to help with this if more needs to be done:

`of = fsspec.open('gdrive://1LpzE8MEUYitOJeMvJAJOUMJDMVbh_GSr', mode='rb', token='anon')`

```
---------------------------------------------------------------------------
HttpError                                 Traceback (most recent call last)
<ipython-input-7-fec500f75b47> in <module>
----> 1 of = fsspec.open('gdrive://1LpzE8MEUYitOJeMvJAJOUMJDMVbh_GSr' class="ansi-blue-fg">, mode='rb', token='anon')

/srv/conda/lib/python3.7/site-packages/fsspec/core.py in open(urlpath, mode, compression, encoding, errors, protocol, newline, **kwargs)
    436         newline=newline,
    437         expand=False,
--> 438         **kwargs
    439     )[0]
    440 

/srv/conda/lib/python3.7/site-packages/fsspec/core.py in open_files(urlpath, mode, compression, encoding, errors, name_function, num, protocol, newline, auto_mkdir, expand, **kwargs)
    285         storage_options=kwargs,
    286         protocol=protocol,
--> 287         expand=expand,
    288     )
    289     if "r" not in mode and auto_mkdir:

/srv/conda/lib/python3.7/site-packages/fsspec/core.py in get_fs_token_paths(urlpath, mode, num, name_function, storage_options, protocol, expand)
    608             )
    609         update_storage_options(options, storage_options)
--> 610         fs = cls(**options)
    611         paths = expand_paths_if_needed(paths, mode, num, fs, name_function)
    612 

/srv/conda/lib/python3.7/site-packages/fsspec/spec.py in __call__(cls, *args, **kwargs)
     56             return cls._cache[token]
     57         else:
---> 58             obj = super().__call__(*args, **kwargs)
     59             # Setting _fs_token here causes some static linters to complain.
     60             obj._fs_token_ = token

/srv/conda/lib/python3.7/site-packages/gdrivefs/core.py in __init__(self, root_file_id, token, access, spaces, **kwargs)
     70         self.root_file_id = root_file_id or 'root'
     71         self.connect(method=token)
---> 72         self.ls("")
     73 
     74     def connect(self, method=None):

/srv/conda/lib/python3.7/site-packages/gdrivefs/core.py in ls(self, path, detail, trashed)
    167                 file_id = self.path_to_file_id(path, trashed=trashed)
    168             files = self._list_directory_by_id(file_id, trashed=trashed,
--> 169                                                path_prefix=path)
    170             self.dircache[path] = files
    171         else:

/srv/conda/lib/python3.7/site-packages/gdrivefs/core.py in _list_directory_by_id(self, file_id, trashed, path_prefix)
    186             response = self.service.list(q=query,
    187                                          spaces=self.spaces, fields=afields,
--> 188                                          pageToken=page_token).execute()
    189             for f in response.get('files', []):
    190                 all_files.append(_finfo_from_response(f, path_prefix))

/srv/conda/lib/python3.7/site-packages/googleapiclient/_helpers.py in positional_wrapper(*args, **kwargs)
    132                 elif positional_parameters_enforcement == POSITIONAL_WARNING:
    133                     logger.warning(message)
--> 134             return wrapped(*args, **kwargs)
    135 
    136         return positional_wrapper

/srv/conda/lib/python3.7/site-packages/googleapiclient/http.py in execute(self, http, num_retries)
    913             callback(resp)
    914         if resp.status >= 300:
--> 915             raise HttpError(resp, content, uri=self.uri)
    916         return self.postproc(resp, content)
    917 

HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files?q=%27root%27+in+parents++and+trashed+%3D+false+&spaces=drive&fields=nextPageToken%2C+files%28name%2Cid%2Csize%2Cdescription%2Ctrashed%2CmimeType%2Cversion%2CcreatedTime%2CmodifiedTime%29&alt=json returned "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.". Details: "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.">
```

**Comment by martindurant** [comment]
I believe this is a genuine limit of the backend. If you wanted to exceed it, you would probably need some API key from google. I am not sure, but it may be possible to circumvent for files where you can get a direct http URL to the resource.

Note that this is happening during list, which is in the code to force an auth - but for anonymous, this is not needed, so you could save some API quota. It may be that list and download have different quotas, so avoiding this line for anon would be a useful change.

**Comment by tjcrone** [comment]
Okay thanks for this information. I only tried to open this file once, and this is the first time I have tried to use gdrivefs. So if the limit was exceeded, the limit is zero, which suggests to me that perhaps something isn't working quite right. I will keep looking into it. If you have any additional thoughts or suggestions please let me know.

Getting anonymous access working for Google Drive in fsspec would be fantastically useful. I wrote something stand-alone for this a couple of years ago (https://github.com/tjcrone/driveanon) which does not rely on their API, but my guess is that this access method won't work anymore.

**Comment by martindurant** [comment]
> my guess is that this access method won't work anymore.

Worth seeing; or worth trying to remove that `ls` in `__init__` for the anon case.

Either way, the code here is no more than a stab at making gdrive work for fsspec, with the least effort (hence relying on the google package). It may well be better done directly with HTTP, like gcsfs is, but that would require some work. It would, however, enable a testing suite built on vcrpy.

**Comment by tjcrone** [comment]
@rabernat, were you able to get this working with anonymous access? Thanks.

**Comment by rabernat** [comment]
No, I don't think so. I only ever used it with a token.

I agree that it would be amazing to unlock the fsspec / gdrive integration. 
It would be great if someone would spend time really digging into this and trying hard to make it work better.

But I also worry that it violates the gdrive terms of service in some way and therefore will always remain a sort of underground hack.

**Comment by martindurant** [comment]
Upon some thinking, I'm not sure how anon ought to work - how do you find the target file? If you already have an ID, then you have the full URL and you can just use HTTPFileSystem, right? Or is it possible to share a full folder for browsing?

**Comment by tjcrone** [comment]
Thanks for your input @rabernat. Do you have specific reason to believe that this would violate terms of service?

@martindurant, I just tried my example from https://github.com/tjcrone/driveanon, and amazingly it still works. Perhaps my code could serve as a roadmap to getting this working with fsspec. Just having the file ID is not enough for large files, because they add a click-to-confirm token which my code gets programatically. Getting a list of blob IDs is not currently possible as my code stands but it was on the roadmap. I think one solution I was considering was to include a list of blob IDs in the folders that I wanted to share, which can be generated after authentication. Ideally the code could get a list of blobs in a folder anonymously but I don't think I solved that problem without scraping.

**Comment by martindurant** [comment]
I am not surprised that accessing the file directly still works - and it's good to know. It's getting information about files and listing that seems to hit the wall.
I haven't looked at your code yet, but I agree that it could easily be the way to go - or some merge of the two. 

Since no one else is likely to spend time here, you would be more than welcome!

On the issue of terms violations, well it seems like google already have their checks in place :) 

>  I don't think I solved that problem without scraping.

You do what you can; both the html output and the api itself (at least the limits) may well change at any moment, it seems.

**Comment by tjcrone** [comment]
@rabernat, can you please describe the process of obtaining and using a token with gdrivefs? Or point me to the docs if they exists? Thanks.

**Comment by martindurant** [comment]
For non-anon, [this line](https://github.com/intake/gdrivefs/blob/master/gdrivefs/core.py#L92) calls [`pydata_google_auth`](https://github.com/pydata/pydata-google-auth) to do the dance.

**Comment by tjcrone** [comment]
I managed to get `token='browser'` to work. It was throwing an error because the cache file did not exist:
```
of = fsspec.open('gdrive://1LpzE8MEUYitOJeMvJAJOUMJDMVbh_GSr', mode='rb', token='browser')
```
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-3-b18e1d573af0> in <module>
----> 1 of = fsspec.open('gdrive://1LpzE8MEUYitOJeMvJAJOUMJDMVbh_GSr' class="ansi-blue-fg">, mode='rb', token='browser')

/srv/conda/lib/python3.7/site-packages/fsspec/core.py in open(urlpath, mode, compression, encoding, errors, protocol, newline, **kwargs)
    436         newline=newline,
    437         expand=False,
--> 438         **kwargs
    439     )[0]
    440 

/srv/conda/lib/python3.7/site-packages/fsspec/core.py in open_files(urlpath, mode, compression, encoding, errors, name_function, num, protocol, newline, auto_mkdir, expand, **kwargs)
    285         storage_options=kwargs,
    286         protocol=protocol,
--> 287         expand=expand,
    288     )
    289     if "r" not in mode and auto_mkdir:

/srv/conda/lib/python3.7/site-packages/fsspec/core.py in get_fs_token_paths(urlpath, mode, num, name_function, storage_options, protocol, expand)
    608             )
    609         update_storage_options(options, storage_options)
--> 610         fs = cls(**options)
    611         paths = expand_paths_if_needed(paths, mode, num, fs, name_function)
    612 

/srv/conda/lib/python3.7/site-packages/fsspec/spec.py in __call__(cls, *args, **kwargs)
     56             return cls._cache[token]
     57         else:
---> 58             obj = super().__call__(*args, **kwargs)
     59             # Setting _fs_token here causes some static linters to complain.
     60             obj._fs_token_ = token

/srv/conda/lib/python3.7/site-packages/gdrivefs/core.py in __init__(self, root_file_id, token, access, spaces, **kwargs)
     69         self.spaces = spaces
     70         self.root_file_id = root_file_id or 'root'
---> 71         self.connect(method=token)
     72         self.ls("")
     73 

/srv/conda/lib/python3.7/site-packages/gdrivefs/core.py in connect(self, method)
     74     def connect(self, method=None):
     75         if method == 'browser':
---> 76             cred = self._connect_browser()
     77         elif method == "cache":
     78             cred = self._connect_cache()

/srv/conda/lib/python3.7/site-packages/gdrivefs/core.py in _connect_browser(self)
     86 
     87     def _connect_browser(self):
---> 88         os.remove(pydata_google_auth.cache.READ_WRITE._path)
     89         return self._connect_cache()
     90 

FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/.config/pydata/pydata_google_credentials.json'
```
Touching the file fixed this error and the credentials file was updated.

**Comment by martindurant** [comment]
Could use a fix :)

**Comment by tjcrone** [comment]
Sorry. That was lame I will fix it.

**Comment by martindurant** [comment]
I might have meant the comment for myself, but my list is pretty long

**Comment by tjcrone** [comment]
No after I left that comment I felt bad because it's an easy fix. Fixing now will PR momentarily.

**Comment by tjcrone** [comment]
Closing because topic is drifting. Thanks for everyone's help here.
