### ISSUE TITLE
Ls only lists files but not directories

### ISSUE THREAD

**Issue by tjcrone** [intake/gdrivefs#18]
gdfs.ls('/') only lists the files in the top-level directory, but does not list subdirectories. I cannot find any function that lists sub-directories. Am I doing it wrong? If so, what is the proper way to list files and also subdirectories? If this is not proper functionality I'm happy to help fix. Thanks. In this example `root_file_id` points to a folder with two files and one subfolder:
```
gdfs = gdrivefs.GoogleDriveFileSystem(root_file_id='1PCBDhk5f3v5PoPCY3Rdcqgy4S_Yj2kCC', token='cache')
files = gdfs.ls('/')
files
```
```
['CRND0103-2017-NY_Millbrook_3_W.csv', 'CRND0103-2017-NY_Millbrook_3_W.nc']
```

**Comment by martindurant** [comment]
I seem to see directories. Perhaps try `ls("")`, without the leading slash?

**Comment by tjcrone** [comment]
Interesting. I still do not see them. Using a slash or not, double quotes or single. Not like the latter should matter. I feel like this might be a caching issue.

**Comment by martindurant** [comment]
I may matter whether the directories in question are yours or shared with you

**Comment by tjcrone** [comment]
I found that a kernel restart was required to see changes in the list of subdirectories. This should be fine I suppose. If there is a way that you think I can improve this please let me know. Thank you for your help.
