### ISSUE TITLE
"This app isn't verified" warning from google oauth

### ISSUE THREAD

**Issue by rabernat** [intake/gdrivefs#7]
When I sign in with `token='browser'`, google shows me this

![image](https://user-images.githubusercontent.com/1197350/68988292-ccf84180-0802-11ea-8708-97a8a3242ec0.png)

I can eventually make it in, but it isn't very confidence-inspiring. I can't figure out how to verify my app. Should be using a different API key maybe?

**Comment by martindurant** [comment]
Interesting... This hasn't been reported for gcsfs, which has the same mechanism available, but I don't think it gets used that much. I suppose the link would tell us how to get the app verified, but there may bee a good chance that we don't actually meet google's guidelines...

**Comment by martindurant** [comment]
Would you be interested in following the link to verify this package as an app?

**Comment by rabernat** [comment]
I couldn't figure out how to do it.

Also, today we got this same message with gcsfs proper.

**Comment by martindurant** [comment]
Tried starting the process for gcsfs (which is more important). Will repeat or dual-purpose that client if successful.

**Comment by martindurant** [comment]
@rabernat, see [this comment](https://github.com/dask/gcsfs/issues/261#issuecomment-663191640), seems like there is a way to get credentials objects now, pandas/pydata blessed.

**Comment by martindurant** [comment]
https://pandas-gbq.readthedocs.io/en/latest/howto/authentication.html#authenticating-with-a-user-account

**Comment by martindurant** [comment]
I am thinking, than gdrive might not be great for throughput, but it's be a great way to share intake catalogues
