### ISSUE TITLE
Anonymous access

### ISSUE THREAD

**Issue by rabernat** [intake/gdrivefs#9]
The link below is a public folder which I can view and access over the web without being logged in to google:

https://drive.google.com/drive/folders/1FQzXM2E28WF6fV7vy1K7HdxNV-w6z_Wx?usp=sharing

The way gdrivefs works now, it's not possible to use in anonymous, un-authenticated mode. What would it take to enable this?

**Comment by tjcrone** [comment]
Was there a solution to this issue? I would like to use gdrivefs (and fsspec) with anonymous read access. Is this possible? Thanks.
